import { BaseEntity } from '../../../shared/domain/model/base-entity';
import { ForecastDataPoint } from './forecast-data-point';

/** Number of days covered by a forecast. */
const FORECAST_DAYS = 7;

/** Weather conditions the simulated model can project. */
const WEATHER_CONDITIONS = ['Soleado', 'Nublado', 'Lluvia ligera'];

/**
 * Formats the local calendar day of a date as `YYYY-MM-DD`.
 *
 * @param date - Date to format.
 * @returns The date in `YYYY-MM-DD` format.
 */
function toIsoDate(date: Date): string {
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${date.getFullYear()}-${month}-${day}`;
}

/** Projection of dish demand for the next days, generated by the forecasting model. */
export class DemandForecast implements BaseEntity {
  /** Unique identifier of the forecast. */
  #id: number;
  /** Moment the forecast was generated, as an ISO 8601 timestamp. */
  #generatedAt: string;
  /** Confidence of the model in the projection, between 0 and 1. */
  #confidenceScore: number;
  /** Weather condition considered by the model. */
  #weatherCondition: string;
  /** Projected demand, one data point per day. */
  #dataPoints: ForecastDataPoint[];

  /**
   * @param forecast - Initial state of the forecast.
   */
  constructor(forecast: {
    id: number;
    generatedAt: string;
    confidenceScore: number;
    weatherCondition: string;
    dataPoints: ForecastDataPoint[];
  }) {
    this.#id = forecast.id;
    this.#generatedAt = forecast.generatedAt;
    this.#confidenceScore = Math.min(1, Math.max(0, forecast.confidenceScore));
    this.#weatherCondition = forecast.weatherCondition;
    this.#dataPoints = [...forecast.dataPoints];
  }

  /** Unique identifier of the forecast. */
  get id(): number {
    return this.#id;
  }

  set id(value: number) {
    this.#id = value;
  }

  /** Moment the forecast was generated, as an ISO 8601 timestamp. */
  get generatedAt(): string {
    return this.#generatedAt;
  }

  set generatedAt(value: string) {
    this.#generatedAt = value;
  }

  /** Confidence of the model in the projection, between 0 and 1. */
  get confidenceScore(): number {
    return this.#confidenceScore;
  }

  set confidenceScore(value: number) {
    this.#confidenceScore = Math.min(1, Math.max(0, value));
  }

  /** Weather condition considered by the model. */
  get weatherCondition(): string {
    return this.#weatherCondition;
  }

  set weatherCondition(value: string) {
    this.#weatherCondition = value;
  }

  /** Projected demand, one data point per day. */
  get dataPoints(): ForecastDataPoint[] {
    return this.#dataPoints;
  }

  set dataPoints(value: ForecastDataPoint[]) {
    this.#dataPoints = [...value];
  }

  /**
   * Expresses the confidence of the model as a percentage.
   *
   * @returns The confidence rounded to a whole percentage, e.g. `82`.
   */
  confidencePercentage(): number {
    return Math.round(this.#confidenceScore * 100);
  }

  /**
   * Adds up the units projected across every day.
   *
   * @returns The total projected units.
   */
  totalProjectedUnits(): number {
    return this.#dataPoints.reduce((total, point) => total + point.projectedUnits, 0);
  }

  /**
   * Finds the day with the highest projected demand.
   *
   * @returns The data point with the most units, or `null` when there are no data points.
   */
  peakDataPoint(): ForecastDataPoint | null {
    return this.#dataPoints.reduce<ForecastDataPoint | null>(
      (peak, point) => (peak === null || point.projectedUnits > peak.projectedUnits ? point : peak),
      null,
    );
  }

  /**
   * Simulates the forecasting model and projects the demand of the next days.
   * There is no real machine learning backend yet, so the projection is random.
   *
   * @param options - Dishes to project, first projected day and random source.
   * @returns A new forecast that has not been saved yet (its identifier is `0`).
   */
  static simulate(options: {
    dishNames: string[];
    startDate?: Date;
    random?: () => number;
  }): DemandForecast {
    const random = options.random ?? Math.random;
    const start = options.startDate ?? new Date();
    const dataPoints = Array.from({ length: FORECAST_DAYS }, (_, index) => {
      const date = new Date(start.getFullYear(), start.getMonth(), start.getDate() + index);
      return new ForecastDataPoint({
        date: toIsoDate(date),
        dayLabel: ForecastDataPoint.dayLabelOf(date),
        dishName: options.dishNames[index % options.dishNames.length],
        projectedUnits: 20 + random() * 60,
      });
    });
    return new DemandForecast({
      id: 0,
      generatedAt: new Date().toISOString(),
      confidenceScore: Number((0.7 + random() * 0.25).toFixed(2)),
      weatherCondition: WEATHER_CONDITIONS[Math.floor(random() * WEATHER_CONDITIONS.length)],
      dataPoints,
    });
  }
}
